// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIO1aNoJwR70ZCgh-ipZKsYkd74R-JDBs',
    appId: '1:904074546034:web:f5e2d162b9f0d2e3762beb',
    messagingSenderId: '904074546034',
    projectId: 'chat-app-b36b8',
    authDomain: 'chat-app-b36b8.firebaseapp.com',
    storageBucket: 'chat-app-b36b8.firebasestorage.app',
    measurementId: 'G-H2Z3BTWQFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxR-NSDSMWPpKFvhyLTsbe8XtjgQK2aN8',
    appId: '1:904074546034:android:d850c0817d732f65762beb',
    messagingSenderId: '904074546034',
    projectId: 'chat-app-b36b8',
    storageBucket: 'chat-app-b36b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Xk95A1Eva353ES7b1PkuZDyji0y1rEQ',
    appId: '1:904074546034:ios:c5c6252c46a5023b762beb',
    messagingSenderId: '904074546034',
    projectId: 'chat-app-b36b8',
    storageBucket: 'chat-app-b36b8.firebasestorage.app',
    iosBundleId: 'com.example.chatAi',
  );
}
